name: Calculate Volumes

on:
  pull_request:
    branches:
      - master

jobs:
  calculate_volumes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run parse_volumes.py
      run: >
        python parse_volumes.py
        --aseg ${{ github.workspace }}/.github/workflows/examples/aseg_volume.csv
        --aparc_lh ${{ github.workspace }}/.github/workflows/examples/aparc_lh_volume.csv
        --aparc_rh ${{ github.workspace }}/.github/workflows/examples/aparc_rh_volume.csv > volumes.json

    - name: Convert JSON to Markdown
      run: |
        python ${{ github.workspace }}/.github/workflows/json_to_md.py --json volumes.json --md volumes.md

    - name: Display CI Summary
      run: |
        echo "Volumes Summary"
        cat volumes.md
      continue-on-error: true

    - name: Create GitHub Actions Summary
      run: |
        echo "## Volumes Summary" >> $GITHUB_STEP_SUMMARY
        cat volumes.md >> $GITHUB_STEP_SUMMARY
