name: 'Build and publish image'

on:
  push:
    branches:
      - '**'
      - '!main'
    tags:
      - v*
env:
  DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}

jobs:
  release:
    name: 'Build image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Install and Configure applications'
        run: |
          apt-get update
          apt-get install -yqq --no-install-recommends \
            ca-certificates \
            git-core
          rm /bin/sh
          ln -s /bin/bash /bin/sh

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Extract metadata (tags, labels) for Docker'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
