name: Generate report from FreeSurfer output pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pipeline
      run: >
        bash pipeline.sh ${{ github.workspace }}/.github/workflows/example_subjects subj1 out
    
    - name: Upload report.pdf artifact
      uses: actions/upload-artifact@v4
      with:
        name: patient_pdf
        path: out/report_gen_output/report.pdf
        retention-days: 1

    - name: Convert JSON to Markdown
      run: |
        python ${{ github.workspace }}/.github/workflows/json_to_md.py --json out/volumes_json_output/data.json --md volumes.md

    - name: Display CI Summary
      run: |
        echo "Volumes Summary"
        cat volumes.md
      continue-on-error: true

    - name: Create GitHub Actions Summary
      run: |
        echo "## Volumes Summary" >> $GITHUB_STEP_SUMMARY
        cat volumes.md >> $GITHUB_STEP_SUMMARY
