name: 'Launch pipeline'

on:
  push:
    branches:
      - '**'
      - '!main'
    tags:
      - v*
env:
  DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}

jobs:
  run-pipeline:
    name: 'Launch pipeline'
    runs-on: ubuntu-latest
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: Setup environment variables
        run: |
          echo "WORKFLOWS_DIR=${{ github.workspace }}/.github/workflows/" >> $GITHUB_ENV
          echo "OUTPUT_DIR=out" >> $GITHUB_ENV

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Build Docker image
        run: |
          docker build -t ci-image .
      
      - name: Run Docker container
        run: |
          docker run \
            -v ${{ env.WORKFLOWS_DIR }}/example_subjects:/root/data \
            -v ${{ env.OUTPUT_DIR }}:/root/out \
            -it --rm ci-image /root/data subj1 /root/out
          --name ci-container ci-image \
      
      - name: Upload report.pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: patient_pdf
          path: ${{ env.OUTPUT_DIR }}/report_gen_output/report.pdf
          retention-days: 1
    
      - name: Convert JSON to Markdown
        run: >
          python ${{ env.WORKFLOWS_DIR }}/json_to_md.py
          --json ${{ env.OUTPUT_DIR }}/volumes_json_output/data.json
          --md volumes.md
  
      - name: Display CI Summary
        run: |
          echo "Volumes Summary"
          cat volumes.md
        continue-on-error: true
  
      - name: Create GitHub Actions Summary
        run: |
          echo "## Volumes Summary" >> $GITHUB_STEP_SUMMARY
          cat volumes.md >> $GITHUB_STEP_SUMMARY
