name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

permissions: write-all

jobs:
  pr-title:
    name: 'Title'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            docs
            ci
            chore
            refactor
            revert
            no-release
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: true
          validateSingleCommit: false
